# Deploy the project to the desired target

# Sample workflow content to call this:
#
# on:
#   workflow_dispatch:
#
# jobs:
#   deploy:
#     uses: PSDI-UK/psdi-github-workflows-public/.github/workflows/deploy.yml@VERSION
#     with:
#       deployment_repo: DEPLOYMENT_REPO_NAME
#       deployment_ref: DEPLOYMENT_REPO_REF
#       environment: production
#       prod: true
#       origin: https://SITE_NAME.psdi.ac.uk
#     secrets:
#       deployment_app_id: ${{ secrets.DEPLOYMENT_APP_ID }}
#       deployment_app_private_key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}

name: Deploy to STFC cluster
run-name: Deploy to STFC cluster
on:
  workflow_call:
    inputs:
      deployment_repo:
        description: "The name of the repo used for deployment of this repo"
        required: true
        type: string
      deployment_ref:
        description: "The ref of the deployment repo to be used"
        required: true
        type: string
      environment:
        description: "The deployment environment (dev, staging, production)"
        required: false
        default: "dev"
        type: string
      prod:
        description: "If true, will run test on the deployed site instead of local"
        required: false
        default: false
        type: boolean
      origin:
        description: "If prod=true, the address of the deployed site to test on (unused if prod=false)"
        required: false
        default: "null"
        type: string
    secrets:
      token:
        description: "GitHub token"
        required: true
      deployment_app_id:
        description: "ID of GitHub app used for authentication"
        required: true
      deployment_app_private_key:
        description: "Private key of GitHub app used for authentication"
        required: true

jobs:
  check-branch:
    # Check that this job is being run on the release branch
    name: Check this is release branch
    runs-on: ubuntu-latest
    steps:
      - name: Check branch (success)
        if: github.ref == 'refs/heads/release'
        run: echo "Success - this is being run on the 'release' branch"
      - name: Check branch (failure)
        if: github.ref != 'refs/heads/release'
        run: |
          echo "ERROR: This workflow can only be run on the 'release' branch"
          false # Command that always fails, to signal the job to fail

  get-latest-release-tag:
    # run on our self hosted github runners enabling access to STFC infrastructure
    name: Get latest release tag
    runs-on: ubuntu-latest
    needs: check-branch
    outputs:
      tag: ${{ steps.get-tag.outputs.TARGET_TAG }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get latest tag in the relase branch
        id: get-tag
        run: |
          TARGET_TAG=$(git tag --sort -version:refname | head -n 1)
          echo "TARGET_TAG=$TARGET_TAG" >> "$GITHUB_OUTPUT"
          echo "Highest version tag found to be = $TARGET_TAG"

  deploy-stfc-k8s:
    needs: get-latest-release-tag
    uses: ./.github/workflows/trigger-deployment.yml
    with:
      deployment_repo: ${{ inputs.deployment_repo }}
      deployment_ref: ${{ inputs.deployment_ref }}
      environment: ${{ inputs.environment }}
      container_tag: ${{ needs.get-latest-release-tag.outputs.tag }}
    secrets:
      deployment_app_id: ${{ secrets.DEPLOYMENT_APP_ID }}
      deployment_app_private_key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}

  # Run a simple test on prod to ensure nothing is broken
  test-prod:
    if: ${{ inputs.prod }}
    name: Test deployment was successful
    needs: deploy-stfc-k8s
    uses: ./.github/workflows/test-gui.yml
    with:
      simple: true
      prod: true
      origin: ${{ inputs.origin }}
    secrets:
      token: ${{ secrets.token }}
